"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.updateAccountSettings = exports.registerUser = exports.migrateLegacyPasswords = exports.loginUser = exports.probeGeminiConnection = exports.getAssistantPlan = exports.askAssistant = exports.getTrendSummary = exports.updateExerciseEntry = exports.getExerciseSummary = exports.deleteExerciseEntry = exports.addExerciseEntry = exports.updateDietEntry = exports.getDietSummary = exports.deleteDietEntry = exports.addWaterIntake = exports.addDietEntry = exports.updateBodyProfile = exports.getBodyProfile = exports.getOverviewSummary = exports.ensureAnalyticsSchema = exports.closePool = void 0;
var shared_cjs_1 = require("./shared.cjs");
Object.defineProperty(exports, "closePool", { enumerable: true, get: function () { return shared_cjs_1.closePool; } });
Object.defineProperty(exports, "ensureAnalyticsSchema", { enumerable: true, get: function () { return shared_cjs_1.ensureAnalyticsSchema; } });
var overview_cjs_1 = require("./overview.cjs");
Object.defineProperty(exports, "getOverviewSummary", { enumerable: true, get: function () { return overview_cjs_1.getOverviewSummary; } });
var body_cjs_1 = require("./body.cjs");
Object.defineProperty(exports, "getBodyProfile", { enumerable: true, get: function () { return body_cjs_1.getBodyProfile; } });
Object.defineProperty(exports, "updateBodyProfile", { enumerable: true, get: function () { return body_cjs_1.updateBodyProfile; } });
var diet_cjs_1 = require("./diet.cjs");
Object.defineProperty(exports, "addDietEntry", { enumerable: true, get: function () { return diet_cjs_1.addDietEntry; } });
Object.defineProperty(exports, "addWaterIntake", { enumerable: true, get: function () { return diet_cjs_1.addWaterIntake; } });
Object.defineProperty(exports, "deleteDietEntry", { enumerable: true, get: function () { return diet_cjs_1.deleteDietEntry; } });
Object.defineProperty(exports, "getDietSummary", { enumerable: true, get: function () { return diet_cjs_1.getDietSummary; } });
Object.defineProperty(exports, "updateDietEntry", { enumerable: true, get: function () { return diet_cjs_1.updateDietEntry; } });
var exercise_cjs_1 = require("./exercise.cjs");
Object.defineProperty(exports, "addExerciseEntry", { enumerable: true, get: function () { return exercise_cjs_1.addExerciseEntry; } });
Object.defineProperty(exports, "deleteExerciseEntry", { enumerable: true, get: function () { return exercise_cjs_1.deleteExerciseEntry; } });
Object.defineProperty(exports, "getExerciseSummary", { enumerable: true, get: function () { return exercise_cjs_1.getExerciseSummary; } });
Object.defineProperty(exports, "updateExerciseEntry", { enumerable: true, get: function () { return exercise_cjs_1.updateExerciseEntry; } });
var trend_cjs_1 = require("./trend.cjs");
Object.defineProperty(exports, "getTrendSummary", { enumerable: true, get: function () { return trend_cjs_1.getTrendSummary; } });
var assistant_cjs_1 = require("./assistant.cjs");
Object.defineProperty(exports, "askAssistant", { enumerable: true, get: function () { return assistant_cjs_1.askAssistant; } });
Object.defineProperty(exports, "getAssistantPlan", { enumerable: true, get: function () { return assistant_cjs_1.getAssistantPlan; } });
Object.defineProperty(exports, "probeGeminiConnection", { enumerable: true, get: function () { return assistant_cjs_1.probeGeminiConnection; } });
var auth_cjs_1 = require("./auth.cjs");
Object.defineProperty(exports, "loginUser", { enumerable: true, get: function () { return auth_cjs_1.loginUser; } });
Object.defineProperty(exports, "migrateLegacyPasswords", { enumerable: true, get: function () { return auth_cjs_1.migrateLegacyPasswords; } });
Object.defineProperty(exports, "registerUser", { enumerable: true, get: function () { return auth_cjs_1.registerUser; } });
Object.defineProperty(exports, "updateAccountSettings", { enumerable: true, get: function () { return auth_cjs_1.updateAccountSettings; } });
